;JUEGO DE LUCES
;ASIGNACION
    CUENTA EQU 0x20
    TIEMPO EQU 0x21
    ESTADO EQU 0x22
    ANTES_A EQU 0x23
    ANTES_B EQU 0x24
; CONFIGURACION DE PIC 
    LIST P=16F877A ; LISTA DE PROGRAMACION 
    INCLUDE P16F877A.INC
    __CONFIG _XT_OSC & _WDT_OFF & _LVP_OFF
;INICIALIZACION
    BSF STATUS,RP0  ;CAMBIO A BANCO 1 
    MOVLW 0x01      ;GRABADO DE 1 PARA ASIGNAR PORTC,0 COMO LECTURA 
    MOVWF TRISC     ;ASIGNACION DE PUERTOC COMO ESCRITURA /LECTURA
    MOVLW B'0000111';PRECARGA DE OPTION REG
    MOVF OPTION_REG ;CONFIGURACION DE PRESCALER 
    CLRF TRISD      ;PONE TODO PORT D COMO SALIDA
    BCF STATUS,RP0  ;VUELTA AL BANCO 0
    MOVLW 0x05      ; CARGA EL VALOR 5
    MOVWF TIEMPO    ; LO PONE EN CUENTA 
    CLRF ESTADO     ;BORRADO DE VALOR RESIDUAL EN ESTADO
    CLRF CUENTA     ;BORRADO DE ESTADO POR RESIDUO
    CLRF ANTES_A    ;"EN ANTES A"
    CLRF ANTES_B    ;"EN ANTES B"
;BUCLE
BUCLE 
    MOVF PORTA,4,W ;COPIA DEL PUERTO A
    MOVWF ANTES_A  ;GUARDADO EN ANTES A
    MOVF PORTB,0,w ;COPIA DEL PUERTO B 
    MOVWF ANTES_B  ;GUARDADO EN ANTES B
    CALL TEMPORIZAR 
EFECTO ADDWL PCL,F  ;SELECCION DE EFECTO 
    GOTO EFECTO_0   ;IR A EFECTO 1 
    GOTO EFECTO_1   ;IR A EFECTO 2 
    GOTO EFECTO_2   ;IR A EFECTO 3
TEMPORIZAR MOVF TIEMPO,W    ;CARGA DE CUENTA DE TIEMPO EN W 
        CALL TABLA  ; PONE 
        
PRECARGA MOVWF CUENTA   ; CARGA EN CUENTA DE TIEMPO 
    MOVLW D'61'     ;   AJUSTE DE PRECARGA 
    MOVWF TMR0      ; ESTABLECER PRECARGA 
    BCF INTCON,T0IF ; RESETEO DE FLAG 
ESPERA BTFSS INTCON,T0IF    ; COMPROBACION DE FLAG 
    GOTO ESPERA     ; SI TODAVIA NO DESBORDO VOLVEMOS A COMPROBAR
    DECFSZ CUENTA,F ; CUANDO LLEGA A 0 LA CUENTA VUELVE 
    GOTO PRECARGA   ; SI NO VUELVE A PRECARGAR EL TIEMPO Y VUELVE A CONTAR
    RETURN
