;JUEGO DE LUCES
;ASIGNACION
    CUENTA EQU 0x20
    TIEMPO EQU 0x21
    ESTADO EQU 0x22
    ANTES_A EQU 0x23
    ANTES_B EQU 0x24
; CONFIGURACION DE PIC 
    LIST P=16F877A ; LISTA DE PROGRAMACION 
    INCLUDE P16F877A.INC
    __CONFIG _XT_OSC & _WDT_OFF & _LVP_OFF
;INICIALIZACION
    BSF STATUS,RP0  ;CAMBIO A BANCO 1 
    MOVLW 0x01      ;GRABADO DE 1 PARA ASIGNAR PORTC,0 COMO LECTURA 
    MOVWF TRISC     ;ASIGNACION DE PUERTOC COMO ESCRITURA /LECTURA
    MOVLW B'0000111';PRECARGA DE OPTION REG
    MOVF OPTION_REG ;CONFIGURACION DE PRESCALER 
    BCF STATUS,RP0  ;VUELTA AL BANCO 0

    CLRF TIEMPO
    CLRF CUENTA
    CLRF ANTES_A
    CLRF ANTES_B
;BUCLE
BUCLE 
    MOVF PORTA,4,W ;COPIA DEL PUERTO A
    MOVWF ANTES_A  ;GUARDADO EN ANTES A
    MOVF PORTB,0,w ;COPIA DEL PUERTO B 
    MOVWF ANTES_B  ;GUARDADO EN ANTES B
    CALL TEMPORIZAR 
TEMPORIZAR 
EFECTO ADDWL PCL,F
    GOTO EFECTO_0
    GOTO EFECTO_1
    GOTO EFECTO_2